# Generated by Django 2.2.7 on 2020-04-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_found',
            old_name='slug',
            new_name='slug1',
        ),
    ]
