# Generated by Django 2.2.7 on 2020-04-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0004_auto_20200409_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_found',
            old_name='thumb',
            new_name='image',
        ),
    ]
